apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-go 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fib-go
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: fib-go
    spec:
      containers:
        - image: quay.io/jduimovich0/fib-go
          imagePullPolicy: Always
          name: container-image
          ports:
            - containerPort: 8080 