apiVersion: apps/v1
kind: Deployment
metadata:
  name: rgb-service-v2
  labels:
    app: rgb-service
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rgb-service
      version: v2
  template:
    metadata:
      labels:
        app: rgb-service
        version: v2
    spec:
      containers:
      - name: demoservice
        image: jduimovich/rgb:red
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
