apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-node-deploy
  labels:
    app: fib
    app.kubernetes.io/name: fib-node-deploy
    app.kubernetes.io/part-of: fib-service  
    app.kubernetes.io/instance : fib-service-in-node
    app.kubernetes.io/component : backend 
    app.openshift.io/runtime : nodejs 
  annotations:  
    container.apparmor.security.beta.kubernetes.io/fib-node-deploy: runtime/default 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fib
  template:
    metadata:
      labels:
        app: fib
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: fib-node-deploy
        image: jduimovich/fib-node:latest
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"
          requests:
            cpu: "100m"
            memory: "32Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
        securityContext:
          capabilities:
            drop:
              - all