apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: frontend
    spec:
      containers:
        - image: quay.io/jduimovich0/frontend
          imagePullPolicy: Always
          name: container-image
          ports:
            - containerPort: 8080 