apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
    app: frontend 
    app.kubernetes.io/name:  frontend-deploy
    app.kubernetes.io/part-of: frontend-service 
    app.kubernetes.io/instance : nginx-html-server
    app.kubernetes.io/component : frontend   
    app.openshift.io/runtime : nginx 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-deploy
        image: jduimovich/frontend:latest
        resources:
          limits:
            cpu: "200m"
            memory: "48Mi"
          requests:
            cpu: "100m"
            memory: "48Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8080
