apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
