apiVersion: apps/v1
kind: Deployment
metadata:
  name: rgb-service-v1
  labels:
    app: rgb-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rgb-service
  template:
    metadata:
      labels:
        app: rgb-service
    spec:
      containers:
      - name: rgb-service
        image: jduimovich/rgb:blue
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /test
            port: 8080
