apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-deploy
  labels:
    app: haproxy
    app.openshift.io/runtime: haproxy
  annotations:
    app.openshift.io/connects-to: '[ {"apiVersion":"apps/v1","kind":"Deployment","name":"fib-node-deploy"}  ]'
    container.apparmor.security.beta.kubernetes.io/haproxy-deploy: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: haproxy-deploy
          image: quay.io/jduimovich0/haproxy:demo
          resources:
            limits:
              cpu: "200m"
              memory: "90Mi"
            requests:
              cpu: "100m"
              memory: "90Mi"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            initialDelaySeconds: 2
            periodSeconds: 5
            httpGet:
              path: /health
              port: 8080
          securityContext:
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: false
