apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-go-deploy
  labels:
    app: fib
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fib
  template:
    metadata:
      labels:
        app: fib
    spec:
      containers:
      - name: fib-go-deploy
        image: jduimovich/fib-go:latest
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        readinessProbe:
          tcpSocket:
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /health
            port: 8083
