apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-node 
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: fib-node
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: fib-node
    spec:
      containers:
        - image: quay.io/jduimovich0/fib-node
          imagePullPolicy: Always
          name: container-image
          ports:
            - containerPort: 8080 