# https://hub.docker.com/_/node 
FROM docker.io/library/node:24.12

# Create and change to the app directory.
WORKDIR /usr/src/app

COPY package*.json ./ 
RUN npm install   
COPY . . 
ENV PORT=8080
EXPOSE $PORT 
RUN npm install -g nodemon 
ENTRYPOINT ["nodemon", "app.js"] 
 