apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-quarkus-deploy
  labels:
    app: fib
    app.kubernetes.io/name: fib-quarkus-deploy
    app.kubernetes.io/part-of: fib-service  
    app.kubernetes.io/instance : fib-service-in-quarkus
    app.kubernetes.io/component : backend 
    app.openshift.io/runtime : quarkus 
  annotations:  
    container.apparmor.security.beta.kubernetes.io/fib-quarkus-deploy: runtime/default 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fib
  template:
    metadata:
      labels:
        app: fib
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: fib-quarkus-deploy
        image: quay.io/jduimovich0/fib-quarkus:demo
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "512Mi"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 5
          httpGet:
            path: /fib
            port: 8080
        securityContext:
          capabilities:
            drop: 
              - AUDIT_CONTROL 
              - AUDIT_READ
              - AUDIT_WRITE
              - BLOCK_SUSPEND
              - BPF
              - CHECKPOINT_RESTORE 
              - DAC_OVERRIDE
              - DAC_READ_SEARCH 
          readOnlyRootFilesystem: false