# Gitops wokflow
  
name: Build and submit Gitops Pull Request 
env:
  REGISTRY_ROOT: docker.io
  REGISTRY: docker.io/jduimovich
  # ⬇️ EDIT with your registry username.

  # ⬇️ EDIT with your registry and registry path.
  REGISTRY_USER: jduimovich
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  # ⬇️ EDIT to log into your OpenShift cluster and set up the context.

  APP_NAME: ""
  TAG: ""
on: [push, workflow_dispatch]
jobs:
  image-ci:
    name: Build and Push Images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '2'
      - name: Determine app name
        if: env.APP_NAME == ''
        run: |
          echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV
      - name: Determine tag
        if: env.TAG == ''
        run: |
          echo "TAG=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV

      - name: Compute Changed Files
        run: |
          source compute_change.sh    
      - name: Build fib-go Dockerfile
        if: env.CHANGE_FIB_GO == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: "fib-go"
          tags: ${{ env.TAG }}
          context: ./services/fib-go
          dockerfiles: ./services/fib-go/Dockerfile
      - name: Build fib-node Dockerfile
        if: env.CHANGE_FIB_NODE == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: "fib-node"
          tags: ${{ env.TAG }}
          context: ./services/fib-node
          dockerfiles: ./services/fib-node/Dockerfile
      - name: Build haproxy Dockerfile
        if: env.CHANGE_HAPROXY == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: "haproxy"
          tags: ${{ env.TAG }}
          context: ./services/haproxy
          dockerfiles: ./services/haproxy/Dockerfile
      - name: Build frontend Dockerfile
        if: env.CHANGE_FRONTEND == 'true'
        uses: redhat-actions/buildah-build@v2
        with:
          image: "frontend"
          tags: ${{ env.TAG }}
          context: ./services/frontend
          dockerfiles: ./services/frontend/Dockerfile
      - uses: actions/setup-java@v2
        if: env.CHANGE_FIB_QUARKUS == 'true' 
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.REGISTRY_USER  }}
          password: ${{  env.REGISTRY_PASSWORD}}
      - name: Build with Maven
        if: env.CHANGE_FIB_QUARKUS == 'true' 
        run: |
          cd services/fib-quarkus  
          export QGRP=-Dquarkus.container-image.group=${{ env.REGISTRY_USER }}
          export QUSER=-Dquarkus.container-image.username=${{ env.REGISTRY_USER }}
          export QPUSH=-Dquarkus.container-image.push=true
          export QTAG=-Dquarkus.container-image.tag=${{ env.TAG }}
          echo "GRP " ${{ env.QGRP }} 
          echo "QUSER " ${{ env.QUSER }} 
          echo "QPUSH " ${{ env.QPUSH }} 
          echo "GRQTAGP " ${{ env.QTAG }} 
          mvn clean package ${{ env.QGRP }} ${{ env.QUSER }} ${{ env.QPUSH }} ${{ env.QTAG }} 
      - name: Push fib-go to registry
        if: env.CHANGE_FIB_GO == 'true'
        uses: redhat-actions/push-to-registry@v1
        with:
          image: "fib-go"
          tag: ${{ env.TAG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Push fib-node to registry
        if: env.CHANGE_FIB_NODE == 'true'
        uses: redhat-actions/push-to-registry@v1
        with:
          image: "fib-node"
          tag: ${{ env.TAG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Push haproxy to registry
        if: env.CHANGE_HAPROXY == 'true'
        uses: redhat-actions/push-to-registry@v1
        with:
          image: "haproxy"
          tag: ${{ env.TAG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
      - name: Push frontend to registry
        if: env.CHANGE_FRONTEND == 'true'
        uses: redhat-actions/push-to-registry@v1
        with:
          image: "frontend"
          tag: ${{ env.TAG }}
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Install  yq
        run: |
          ls -al 
          export VERSION=v4.2.0  
          export BINARY=yq_linux_amd64
          wget -q https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O ./yq
          chmod +x ./yq

      - name: Patch Deployment YAML with new image references
        if: env.CHANGE_ANY == 'true'
        run: |
          if [ "${{ env.CHANGE_FRONTEND }}" = "true"]; then
            ./yq  e '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/frontend:${{ env.TAG }}"' deploy/frontend/deployment.yaml -i
          fi
          if [ "${{ env.CHANGE_HAPROXY }}" = "true" ]; then   
            ./yq  e '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/haproxy:${{ env.TAG }}"' deploy/haproxy/deployment.yaml  -i
          fi
          if [ "${{ env.CHANGE_FIB_GO }}" = "true" ]; then   
            ./yq  e '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/fib-go:${{ env.TAG }}"' deploy/services/fib-go/deployment.yaml  -i
          fi
          if [ "${{ env.CHANGE_FIB_NODE }}" = "true" ]; then 
            ./yq  e '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/fib-node:${{ env.TAG }}"' deploy/services/fib-node/deployment.yaml  -i
          fi 
          if [ "${{ env.CHANGE_FIB_QUARKUS }}" = "true" ]; then 
            ./yq  e '.spec.template.spec.containers[0].image = "${{ env.REGISTRY }}/fib-quarkus:${{ env.TAG }}"' deploy/services/fib-quarkus/deployment.yaml  -i
          fi 
      - name: Show list of current images
        run: |
          ./yq  e '.spec.template.spec.containers[0].image' deploy/frontend/deployment.yaml
          ./yq  e '.spec.template.spec.containers[0].image' deploy/haproxy/deployment.yaml
          ./yq  e '.spec.template.spec.containers[0].image' deploy/services/fib-go/deployment.yaml
          ./yq  e '.spec.template.spec.containers[0].image' deploy/services/fib-node/deployment.yaml
          ./yq  e '.spec.template.spec.containers[0].image' deploy/services/fib-quarkus/deployment.yaml

      - name: Cleanup
        run: |
          rm -rf ./yq
          rm -rf  kubeconfig.yaml
          rm -rf  *digest.txt
          rm -rf  tmp_*
      - name: Create Pull Request to update changes in repo
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Deploy with tag ${{ env.TAG }} for commit ${{ github.event.head_commit.message }}'
          commit-message: 'New deployment images with tag ${{ env.TAG }}'
