# This is a basic workflow to help you get started with Actions

name: Snyk Action Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan:
    name: Scan YAML Artifacts with Snyk
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      - name: Run Snyk to check frontend deployment
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: frontend/deploy/deployment.yaml    
      - name: Rename for merging 
        run: | 
          mv snyk.sarif frontend-deployment-snyk.sarif  
      - name: Upload Scan Results  
        uses: actions/upload-artifact@v2
        with: 
          name: frontend-deployment-snyk.sarif  
          path: frontend-deployment-snyk.sarif   
      - name: Run Snyk to check frontend service 
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: frontend/deploy/service.yaml    
      - name: Rename for merging 
        run: | 
          mv snyk.sarif frontend-service-snyk.sarif  
      - name: Upload Scan Results  
        uses: actions/upload-artifact@v2
        with: 
          name: frontend-service-snyk.sarif  
          path: frontend-service-snyk.sarif     
      - name: Bootstrap and Merge
        run: |  
          cp frontend-service-snyk.sarif  merged.sarif      
          node merge.js merged.sarif  frontend-service-snyk.sarif   
          node merge.js merged.sarif  frontend-deployment-snyk.sarif  

      - name: Run Snyk to check fib-go deployment
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: services/fib-go/deploy/deployment.yaml    
      - name: Rename for merging 
        run: | 
          mv snyk.sarif fib-go-deployment-snyk.sarif  
      - name: Upload Scan Results  
        uses: actions/upload-artifact@v2
        with: 
          name: fib-go-deployment-snyk.sarif  
          path: fib-go-deployment-snyk.sarif   
      - name: Run Snyk to check frontend service 
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: services/fib-go/deploy/service.yaml    
      - name: Rename for merging 
        run: | 
          mv snyk.sarif fib-go-service-snyk.sarif  
      - name: Upload Scan Results  
        uses: actions/upload-artifact@v2
        with: 
          name: fib-go-service-snyk.sarif  
          path: fib-go-service-snyk.sarif    
          
      - name: Bootstrap and Merge
        run: |   
          node merge.js merged.sarif  fib-go-service-snyk.sarif 
          node merge.js merged.sarif  fib-go-deployment-snyk.sarif 

      - name: Run Snyk to check fib-node deployment
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: services/fib-node/deploy/deployment.yaml    
      - name: Rename for merging 
        run: | 
          mv snyk.sarif fib-node-deployment-snyk.sarif  
      - name: Upload Scan Results  
        uses: actions/upload-artifact@v2
        with: 
          name: fib-node-deployment-snyk.sarif  
          path: fib-node-deployment-snyk.sarif   
      - name: Run Snyk to check frontend service 
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: services/fib-node/deploy/service.yaml    
      - name: Rename for merging 
        run: | 
          mv snyk.sarif fib-node-service-snyk.sarif  
      - name: Upload Scan Results  
        uses: actions/upload-artifact@v2
        with: 
          name: fib-node-service-snyk.sarif  
          path: fib-node-service-snyk.sarif    
      - name: Bootstrap and Merge
        run: |   
          node merge.js merged.sarif  fib-node-service-snyk.sarif 
          node merge.js merged.sarif  fib-node-deployment-snyk.sarif 
 

      - name: Upload merged Results  
        uses: actions/upload-artifact@v2
        with: 
          name:  merged.sarif 
          path: merged.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: merged.sarif 