# This is a basic workflow to help you get started with Actions

name: Snyk Action Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan:
    name: Scan Repo with Snyk
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      - name: Run Snyk to check frontend  
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: frontend/deploy/deployment.yaml    
      - name: Rename for merging 
        run: | 
          mv snyk.sarif frontend-snyk.sarif 
          cp frontend-snyk.sarif   merged.sarif
      - name: Upload Scan Results  
        uses: actions/upload-artifact@v2
        with: 
          name:  frontend-snyk.sarif    
          path: frontend-snyk.sarif    

      - name: Run Snyk to check fib-go
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: services/fib-go/deploy/deployment.yaml    
      - name: Rename for merging 
        run: | 
          mv snyk.sarif fib-go-snyk.sarif 
          node merge.js merged.sarif fib-go-snyk.sarif 
      - name: Upload Scan Results  
        uses: actions/upload-artifact@v2
        with: 
          name:  fib-go-snyk.sarif    
          path: fib-go-snyk.sarif    
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: merged.sarif 