# This is a basic workflow to help you get started with Actions

name: Snyk Action Integration

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan:
    name: Scan YAML Artifacts with Snyk
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 

      - name: Run Snyk to check frontend deployment
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: frontend/deploy/deployment.yaml    
      - name: Combine Snyk Sarif Output
        run: | 
          bash snyk-rename   

      - name: Run Snyk to check frontend service 
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: frontend/deploy/service.yaml  
      - name: Combine Snyk Sarif Output
        run: | 
          bash snyk-rename   

      - name: Run Snyk to check fib-go deployment
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: services/fib-go/deploy/deployment.yaml    
      - name: Combine Snyk Sarif Output
        run: | 
          bash snyk-rename   

      - name: Run Snyk to check fib-node deployment
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: services/fib-node/deploy/deployment.yaml    
      - name: Combine Snyk Sarif Output
        run: | 
          bash snyk-rename   

      - name: Run Snyk to check fib-quarkus deployment
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: services/fib-quarkus/deploy/deployment.yaml    
      - name: Combine Snyk Sarif Output
        run: | 
          bash snyk-rename   

      - name: Save all sarif files
        run: |  
          mkdir -p uploads
          mv *.sarif  uploads 

      - name: Upload merged Results  
        uses: actions/upload-artifact@v2
        with: 
          name: uploads
          path: uploads
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: uploads/merged.sarif 